Dungeon_Generation: Dungeon_Generation.o
	gcc Dungeon_Generation.o -o Dungeon_Generation

Dungeon_Generation.o: Dungeon_Generation.c Dungeon_Generation.h
	gcc -c Dungeon_Generation.c -Wall -ggdb -o Dungeon_Generation.o

clean:
	rm -f Dungeon_Generation Dungeon_Generation.o *~
